hamroProject/hamroProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('', include('product.urls')),
]

hamroProject/login/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
	path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
	path('home', views.home, name='home'),
	#path(''. views.login),
	path('register/', views.signup, name='register'),
	path('setsession',views.setsession),
	path('getsession',views.getsession),
	path('getcookie',views.getcookie),
	path('setcookie',views.setcookie)
]

hamroProject/product/urls.py
from django.contrib import admin  
from django.urls import path  
from product import views  
urlpatterns = [
    path('product/', views.product),  
    path('show/', views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy), 
    path('getjson', views.getjson),
    path('raw_sql', views.raw_sql),
    path('api/get_products/', views.get_products, name="get_products"),
    path('api/pay/', views.PaymentView.as_view(), name="pay"), 
]

hamroProject/login/models.py
from django.db import models

# Create your models here.
class Login(models.Model):
	first_name = models.CharField(max_length=20)
	password = models.CharField(max_length=30)

class Register(models.Model):
	firstname = models.CharField(max_length=50)
	lastname = models.CharField(max_length=50)
	email = models.EmailField(max_length=50)
	password = models.CharField(max_length=50)
	confirmpassword = models.CharField(max_length=50)

hamroProject/product/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
	first_name = models.CharField(max_length=20)
	last_name = models.CharField(max_length=20)

class Product(models.Model):
	pid = models.CharField(max_length=20)
	pname = models.CharField(max_length=100)
	pprice = models.IntegerField()
	class Meta:
		db_table = "products"

class Payment(models.Model):
	customer_id = models.CharField(max_length=20)
	amount = models.IntegerField()

	def __str__(self):
		return "{} - {}".format(self.customer_id, self.amount)

	class Meta:
		db_table = "payments"

hamroProject/login/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ("username","password")
		labels = {
			'username': 'Username',
			'password': 'Password'
		}

		#selecting some fields
		#fields = ('first_name', 'last_name')

class SignupForm(forms.ModelForm):
	password = forms.CharField(label='Password', widget=forms.PasswordInput)
	confirmpassword = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ("username","first_name","last_name","email","password")
		labels = {
			'firstname': 'First name',
			'lastname': 'Last Name',
			'email': 'Email'
		}

hamroProject/product/forms.py
from django import forms
from product.models import Product

#from django.core import serializers
#from product.models import Payment

class ProductForm(forms.ModelForm):
	class Meta:
		model = Product
		fields = "__all__"

'''
class PaymentSerializer(serializers.ModelSerializer):
	class Meta:
		model = Payment
		fields = "__all__"
'''

hamroProject/login/views.py
from django.shortcuts import render, redirect
from django.template import loader, RequestContext
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import login as auth_login, authenticate

# Create your views here.
from login.forms import LoginForm, SignupForm

from django.http import HttpResponse
import datetime

'''
#csrf = Cross site request forgery
@csrf_protect
def login(request):
	if request.method == 'POST':
		login = LoginForm(request.POST)
		if login.is_valid():
			return HttpResponse("Logged In")
		else:
			return HttpResponse("Error while logging in")
	else:
		csrfContext = RequestContext(request)
		login_form = LoginForm()
		return render(request,'login.html',{'form': login_form},csrfContext)
'''

@csrf_protect
def signup(request):
	if request.method == 'POST':
		signup = SignupForm(request.POST)
		if signup.is_valid():
			user = signup.save()
			user.set_password(user.password)
			user.save()
			username = user.username
			raw_password = signup.cleaned_data.get('password')
			user = authenticate(username=username, password=raw_password)
			if user is not None:
				auth_login(request, user)
				return redirect('show/')

		return HttpResponse("Error while lregistering it")
	else:
		csrfContext = RequestContext(request)
		signup_form = SignupForm()
		return render(request,'register.html',{'form': signup_form},csrfContext)

def home(request):
	return render(request, 'home.html')

def setsession(request):
	request.session['name']='test'
	request.session['address']='ktm'
	return HttpResponse("session has been set.")

def getsession(request):
	name = request.session['name']
	address = request.session['address']
	return HttpResponse("Name: {0}, Address: {1}".format(name,address))

def setcookie(request):
	response = HttpResponse("Cookie has been set")
	response.set_cookie('age', datetime.datetime.now())
	return response

def getcookie(request):
	age = request.COOKIES['age']
	return HttpResponse("age: {0}".format(age))

hamroProject/product/views.py
from django.shortcuts import render, redirect  
from product.forms import ProductForm  
from product.models import Product  
from django.http import JsonResponse
from rest_framework.views import APIView
from .models import Payment

from .serializers import PaymentSerializer, ProductSerializer
 
def product(request):  
    if request.method == "POST":  
        form = ProductForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = ProductForm()  
    return render(request,'index.html',{'form':form})  

def show(request):  
    products = Product.objects.all()  
    return render(request,"show.html",{'products':products})  

def edit(request, id):  
    product = Product.objects.get(id=id)  
    return render(request,'edit.html', {'product':product}) 

def update(request, id):  
    product = Product.objects.get(id=id)  
    form = ProductForm(request.POST, instance = product)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'product': product})
  
def destroy(request, id):  
    product = Product.objects.get(id=id)  
    product.delete()  
    return redirect("/show")

def raw_sql(request):
	name = ''
	for p in Product.objects.raw('SELECT * FROM products'):
		name = nme + " " + p.pname
	return JsonResponse({'result':name})

def getjson(request):
	return JsonResponse({'name':'broadway'})

def get_products(request):
	products = Product.objects.all()
	serializer = ProductSerializer(products, many=True)
	return JsonResponse(serializer.data, safe=False)

class PaymentView(APIView):
	def post(self, request):
		serializer = PaymentSerializer(data=request.data)
		if serializer.is_valid():
			serializer.save()
			return JsonResponse({'message':'Payment was Successful.'})
		return JsonResponse({'message':'Payment was unsuccessful.'})

	def get(self, request):
		payments = Payment.objects.all()
		serializer = PaymentSerializer(payments, many=True)
		return JsonResponse(serializer.data, safe=False)

'''
def pay(request):
	payment_serializer = PaymentSerializer(data = request.data)
	if payment_serializer.is_valid():
		payment_serializer.save()
		return JsonResponse({'success': True})
	return JsonResponse({'success': False})
'''

hamroProject/login/templates/home.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Home</title>  
</head>  
<body>  
    <div>
        <h1>Home Page</h1>
        <a  href="{% url 'logout' %}">Logout</a>
    </div>
</body>  
</html>

hamroProject/login/templates/login.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Login</title>  
    {% load static %}
    {% load crispy_forms_tags %}
    <link href="{% static '/css/login_style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>  
<body>  
    <div class="login-form">
        <form method="POST" class="post-form"> 
            {% csrf_token %}
            <h2 class="text-center">Log in</h2>
            <div class="form-group">  
                {{ form | crispy }}
            </div>  
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Log in</button>
            </div>
            <div class="clearfix">
                <label class="pull-left checkbox-inline"><input type="checkbox"> Remember me</label>
                <a href="#" class="pull-right">Forgot Password?</a>
            </div>  
        </form>
        <p class="text-center"><a href="{% url 'register' %}">Create an Account</a></p>
    </div>
</body>  
</html>

hamroProject/login/templates/logout.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Home</title>  
</head>  
<body>  
    <div>
        <h1>You are logged out!</h1 >
        <a  href="{% url 'login' %}">Log in again</a>
    </div>
</body>  
</html>

hamroProject/login/templates/register.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Login</title>  
    {% load static %}
    {% load crispy_forms_tags %}
    <link href="{% static '/css/login_style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>  
<body>  
    <div class="login-form">
        <form method="POST" class="post-form"> 
            {% csrf_token %}
            <h2 class="text-center">Sign up</h2>
            <div class="form-group">  
                {{ form | crispy }}
            </div>  
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Sign up</button>
            </div> 
        </form>
        <p class="text-center"><a href="{% url 'login' %}">Back to Login</a></p>
    </div>
</body>  
</html>

hamroProject/product/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{product.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="pid" id="id_pid" required maxlength="20" value="{{ product.pid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="pname" id="id_pname" required maxlength="100" value="{{ product.pname }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product Price:</label>  
    <div class="col-sm-4">  
        <input type="text" name="pprice" id="id_pprice" required maxlength="254" value="{{ product.pprice }}" />  
    </div>
    </div>    
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

hamroProject/product/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
</head>  
<body>  
<form method="POST" class="post-form" action="/product/">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product Id:</label>  
    <div class="col-sm-4">  
      {{ form.pid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product Name:</label>  
    <div class="col-sm-4">  
      {{ form.pname }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product Price:</label>  
    <div class="col-sm-4">  
      {{ form.pprice }}  
    </div>   
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>

hamroProject/product/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Products</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Product ID</th>  
        <th>Product Name</th>  
        <th>Product Price</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for product in products %}  
    <tr>  
        <td>{{ product.pid }}</td>  
        <td>{{ product.pname }}</td>  
        <td>{{ product.pprice }}</td>  
        <td>  
            <a href="/edit/{{ product.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ product.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/product" class="btn btn-primary">Add New Record</a></center>  
&nbsp;&nbsp;<a  href="{% url 'logout' %}">Logout</a>
</body>  
</html>  